config/routes.rb
ProtectedApp::Application.routes.draw do
  resources :items


  resources :folders


  get "static_pages/home"

  devise_for :users

  root :to => "static_pages#home"
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :parent_id, :name

  has_ancestry
  belongs_to :user
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :folder_id, :login, :login_url, :notes, :password, :title

  belongs_to :folder
  belongs_to :user

  def self.search(search)
    if search
      where(title: search)
    else
      order(:title)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :folders
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :get_items

  def get_items
    if user_signed_in?
      @search_items = current_user.items.order("title").pluck(:title)
    end
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_filter :authenticate_user!

  # GET /folders
  # GET /folders.json
  def index
    @folders = current_user.folders.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @folders }
    end
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    @folder = current_user.folders.find(params[:id])
    @items_inside_folder = @folder.items.order("title")
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @folder }
    end
  end

  # GET /folders/new
  # GET /folders/new.json
  def new
    @folder = current_user.folders.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @folder }
    end
  end

  # GET /folders/1/edit
  def edit
    @folder = current_user.folders.find(params[:id])
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = current_user.folders.build(params[:folder])

    respond_to do |format|
      if @folder.save
        format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
        format.json { render json: @folder, status: :created, location: @folder }
      else
        format.html { render action: "new" }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /folders/1
  # PUT /folders/1.json
  def update
    @folder = current_user.folders.find(params[:id])

    respond_to do |format|
      if @folder.update_attributes(params[:folder])
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder = current_user.folders.find(params[:id])
    @folder.destroy

    respond_to do |format|
      format.html { redirect_to folders_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!

  # GET /items
  # GET /items.json
  def index
    @items = current_user.items.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = current_user.items.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = current_user.items.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = current_user.items.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = current_user.items.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @last_folders = current_user.folders.order("updated_at").limit(10)
      @last_items = current_user.items.order("updated_at").limit(10)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.collection_select :parent_id, Folder.order(:name), :id, :name, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<div class="row-fluid">
  <div class="span9">
    <ul class="breadcrumb">
      <li><a href="#">Home</a> <span class="divider">/</span></li>
    </ul>
  </div>
  <div class="span3">
    <%= link_to new_folder_path, class: "btn btn-block btn-success" do %>
      <i class="icon-white icon-plus-sign"></i> New folder
    <% end %>
  </div>
</div>

<div class="row-fluid">
  <div class="span12">
    <table class="table table-striped">
      <tr>
        <th>Root folders</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <% Folder.roots.each do |folder| %>
        <tr>
          <td><%= link_to folder.name, folder %></td>
          <td><%= link_to "Edit", edit_folder_path(folder), class: "btn btn-mini btn-warning" %></td>
          <td><%= link_to "Delete", folder, method: :delete, class: "btn btn-mini btn-danger",
                  data: { confirm: "Are you sure you want to delete this folder: '#{folder.name}' and all its content?" } %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/folders/new.html.erb
<h1>New folder</h1>

<%= render 'form' %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<% content_for :title, @folder.name %>

<div class="row-fluid">
  <div class="span9">
    <ul class="breadcrumb">
      <li><%= link_to_unless_current("Home", {:action => "index"}) %> <span class="divider">/</span></li>
      <% @folder.ancestors.each do |folder| %>
        <li><%= link_to folder.name, folder %> <span class="divider">/</span></li>
      <% end %>
      <li class="active"><%= @folder.name %></li>
    </ul>
  </div>
  <div class="span3">
    <%= link_to new_folder_path, class: "btn btn-block btn-success" do %>
      <i class="icon-white icon-plus-sign"></i> New folder
    <% end %>
  </div>
</div>

<div class="row-fluid">
  <div class="span12">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <% @folder.children.each do |subfolder| %>
        <tr>
          <td>
            <%= link_to subfolder do %>
              <i class="icon-folder-close"></i> <%= subfolder.name %>
            <% end %>
          </td>
          <td><%= link_to "Edit", edit_folder_path(subfolder), class: "btn btn-mini btn-warning" %></td>
          <td><%= link_to "Delete", subfolder, method: :delete, class: "btn btn-mini btn-danger",
                  data: { confirm: "Are you sure you want to delete this folder: '#{subfolder.name}' and all its content?" } %></td>
        </tr> 
      <% end %>
      <% @items_inside_folder.each do |item| %>
        <tr>
          <td>
            <%= link_to item do %>
              <i class="icon-circle-arrow-right"></i> <%= item.title %>
            <% end %>
          </td>
          <td><%= link_to "Edit", edit_item_path(item), class: "btn btn-mini btn-warning" %></td>
          <td>
            <%= link_to "Delete", item, method: :delete, class: "btn btn-mini btn-danger", data: {confirm: "Are you sure you want to delete this item?"} %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_for(@item, :html => {class: "form-horizontal"}) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :folder_id, class: "control-label" %>
    <div class="controls">
      <%= f.collection_select(:folder_id, current_user.folders.order("name"), :id, :name) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :login, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :login %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :password %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :login_url, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :login_url %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :notes, class: "control-label" %>
    <div class="controls">
      <%= f.text_area :notes %>
    </div>
  </div>
  
  <div class="controls">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>
<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped">
            <tr>   
                <th>Folder</th>
                <th>Title</th>
                <th>Login</th>
                <th>URL</th>
                <th>View</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            <% @items.each do |item| %>
                <tr>
                    <td><%= link_to item.folder.name, item.folder %></td>
                    <td><%= item.title %></td>
                    <td><%= item.login %></td>
                    <td><%= link_to item.login_url, item.login_url, target: "_blank" %></td>
                    <td>
                        <%= link_to item, class: "btn"  do%>
                            <i class="icon-eye-open"></i>
                        <% end %>
                    </td>
                    <td>
                        <%= link_to edit_item_path(item), class: "btn btn-warning" do %>
                            <i class="icon-white icon-edit"></i>
                        <% end %>
                    </td>
                    <td>
                        <%= link_to item, method: :delete, class: "btn btn-danger",
                            data: { confirm: "Are you sure you want to delete #{item.title}?" } do %>
                            <i class="icon-white icon-trash"></i>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row-fluid">
  <div class="span3">
    <%= link_to edit_item_path(@item), class: "btn btn-warning btn-block" do %>
      <i class="icon-white icon-edit"></i> Edit item
    <% end %>
  </div>
  <div class="span9">
    <ul class="breadcrumb">
      <li><%= link_to "Home", root_path %> <span class="divider">/</span></li>
      <% @item.folder.ancestors.each do |folder| %>
        <li><%= link_to folder.name, folder %> <span class="divider">/</span></li>
      <% end %>
      <li class="active"><%= link_to @item.folder.name, @item.folder %></li>
    </ul>
  </div>
</div>

<div class="row-fluid">
  <div class="span12">
    <p>
      <b>Title:</b>
      <%= @item.title %>
    </p>

    <p>
      <b>Login:</b>
      <%= @item.login %>
    </p>

    <p>
      <b>Password:</b>
      <%= @item.password %>
    </p>

    <p>
      <b>Login url:</b>
      <%= @item.login_url %>
    </p>

    <p>
      <b>Notes:</b>
      <%= @item.notes %>
    </p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Protected App", "/", class: "brand" %>
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <% if user_signed_in? %>
        <div class="nav-collapse collapse">
          <ul class="nav pull-right">
            <li>
              <%= form_tag(items_path, :method => "get", class: "navbar-form") do %>
                <%= text_field_tag :search, params[:search], class: "span3", placeholder: "Search your files", "data" => {"provide" => "typeahead", "source" => @search_items} %>
                <%= submit_tag "Search", class: "btn", name: nil %>
              <% end %>
              <!--<form class="navbar-form">
                <input type="text" class="span4" placeholder="Search your files">
                <button type="submit" class="btn">Submit</button>
              </form>-->
            </li>
            <li class="dropdown">
              <%= link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
                <%= current_user.email %> <b class="caret"></b>
              <% end %>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="icon-off"></i> Log out
                  <% end %>
                </li>
              </ul>
            </li>
          </ul>
        </div>
       <% end %> 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Protected App | <%= content_for?(:title) ? yield(:title) : "Safe passwords" %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <div class="row-fluid">
      <div class="span12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <div class="row-fluid">
    <div class="span6 last_items">
      <% if @last_folders.count == 0 %>
        <%= link_to "Add a new item", "#", class: "btn btn-block btn-warning disabled" %>
      <% else %>
        <%= link_to new_item_path, class: "btn btn-block btn-warning" do %>
          <i class="icon-white icon-plus-sign"></i> Add a new item
        <% end %>
      <% end %>
      <div class="well">
        <ul class="nav nav-list">
          <li class="nav-header">Your Last Items</li>
          <% @last_items.each do |item| %>
            <li><%= link_to item.title, item %></li>
          <% end %>
          <li class="divider"></li>
          <li><%= link_to "See all", items_path %></li>
        </ul>
      </div>
    </div>
    <div class="span6 last_folders">
      <%= link_to new_folder_path, class: "btn btn-success btn-block" do %>
        <i class="icon-white icon-plus-sign"></i> New folder
      <% end %>
      <div class="well">
        <ul class="nav nav-list">
          <li class="nav-header">Your Last Folders</li>
          <% @last_folders.each do |folder| %>
            <li><%= link_to folder.name, folder %></li>
          <% end %>
          <li class="divider"></li>
          <li><%= link_to "See all", folders_path %></li>
        </ul>
      </div>
    </div>
  </div>
<% else %>
  <div class="well home">
    <h1>Protected App</h1>
    <h3>Keep all your passwords in a safe place</h3>
    <div class="row-fluid">
      <div class="span6">
        <%= link_to new_user_registration_path, class: "btn btn-large btn-block btn-primary" do %>
          <i class="icon-white icon-user"></i> Create a new account
        <% end %>
      </div>
      <div class="span6">
        <%= link_to new_user_session_path, class: "btn btn-large btn-block" do %>
          <i class="icon-play-circle"></i> Log in
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>